config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: 'static#home'
  
  resources :tv_shows
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tv_show.rb
class TvShow < ApplicationRecord

    validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

    def home

    end

end

app/controllers/tv_shows_controller.rb
class TvShowsController < ApplicationController
    def index
        @tv_shows = TvShow.all
    end

    def new
        @tv_show = TvShow.new
    end

    def create
        @tv_show = TvShow.new(tv_show_params)

        if @tv_show.save
            redirect_to tv_shows_path
        else  
            flash.now[:error] = @tv_show.errors.full_messages
            render :new
        end
    end

    private

        def tv_show_params
            params.require(:tv_show).permit(:name)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/tv_shows_helper.rb
module TvShowsHelper
end

app/views/layouts/_nav.html.erb
<nav class="blue darken-4">
    <div class="container"> 
        <%= link_to "Home", root_path, class: "brand-logo, left" %> 
        <ul class="right">
        <% unless user_signed_in? %>
            <li><%= link_to "Login", new_user_session_path %></li>
            <li><%= link_to "Signup", new_user_registration_path %></li>
        <% else %>
            <li><%= link_to "Tv Shows", tv_shows_path %></li>
            <li><%= link_to "Add Tv Show", new_tv_show_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: "DELETE" %></li>
        <% end %>
        </ul> 
    </div>
</nav>

app/views/layouts/_wrapper.html.erb
<div class="container white" style="padding: 10px; margin-top: 10px;">
    <%= yield %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FavoriteShowsCollection</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
     
     <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
            
  
  </head>

  <body class="light-blue">
    <%= render 'layouts/nav' %>
    <%= yield %>
  </body>
</html>

app/views/tv_shows/_form_errors.html.erb
<% if flash[:error] %>
    <div class="red">
        <ul>
            <% flash[:error].each do |error| %>
                <li><%= error %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/tv_shows/_tv_show.html.erb
<div class="col s4 m4 l4">
    <div class="card small">
        <div class="card-content blue-text text-darken-4">
            <span class="card-title"><%= tv_show.name %></span>
            <p>Description: WIP</p>
        </div>
        <div class="card-action blue darken-4">
            <%= link_to "More Information", tv_show_path(tv_show) %>
        </div>
    </div>
</div>

app/views/tv_shows/index.html.erb
<%= render 'layouts/wrapper' do %>
    <h3 class="center">Tv Shows</h3>
    <div class="row">
        <%= render @tv_shows %>
    </div>
<% end %>

app/views/tv_shows/new.html.erb
<%= render 'layouts/wrapper' do %>
    <h3 class="center blue-text text-darken-4">Add Tv Show</h3>
    <div class="container">
        <%= render "tv_shows/form_errors" %>
        <%= form_for @tv_show do |f| %>
            <div class="input-field">
                <%= f.label :name %>
                <%= f.text_field :name %>
            </div>

            <%= f.submit "Add Tv Show", class: "btn blue darken-4" %>
        <% end %>
    </div>
<% end %>